# Generated by Django 2.2.16 on 2020-10-29 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('pursose', models.TextField()),
                ('terget', models.TextField()),
                ('course', models.TextField()),
                ('textbook', models.TextField()),
                ('evaluation', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('time', models.CharField(max_length=20)),
                ('t_mail', models.CharField(max_length=200)),
                ('subjecturl', models.TextField()),
                ('sllabus', models.TextField()),
                ('homework', models.TextField()),
                ('lesson', models.TextField()),
                ('regi', models.CharField(max_length=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('pursose', models.TextField()),
                ('terget', models.TextField()),
                ('course', models.TextField()),
                ('textbook', models.TextField()),
                ('evaluation', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('time', models.CharField(max_length=20)),
                ('t_mail', models.CharField(max_length=200)),
                ('subjecturl', models.TextField()),
                ('sllabus', models.TextField()),
                ('homework', models.TextField()),
                ('lesson', models.TextField()),
                ('regi', models.CharField(max_length=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('pursose', models.TextField()),
                ('terget', models.TextField()),
                ('course', models.TextField()),
                ('textbook', models.TextField()),
                ('evaluation', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('time', models.CharField(max_length=20)),
                ('t_mail', models.CharField(max_length=200)),
                ('subjecturl', models.TextField()),
                ('sllabus', models.TextField()),
                ('homework', models.TextField()),
                ('lesson', models.TextField()),
                ('regi', models.CharField(max_length=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('pursose', models.TextField()),
                ('terget', models.TextField()),
                ('course', models.TextField()),
                ('textbook', models.TextField()),
                ('evaluation', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('time', models.CharField(max_length=20)),
                ('t_mail', models.CharField(max_length=200)),
                ('subjecturl', models.TextField()),
                ('sllabus', models.TextField()),
                ('homework', models.TextField()),
                ('lesson', models.TextField()),
                ('regi', models.CharField(max_length=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('pursose', models.TextField()),
                ('terget', models.TextField()),
                ('course', models.TextField()),
                ('textbook', models.TextField()),
                ('evaluation', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('time', models.CharField(max_length=20)),
                ('t_mail', models.CharField(max_length=200)),
                ('subjecturl', models.TextField()),
                ('sllabus', models.TextField()),
                ('homework', models.TextField()),
                ('lesson', models.TextField()),
                ('regi', models.CharField(max_length=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
