from django.urls import path
from . import views

urlpatterns = [
    #path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('course/', views.course, name='course'),
    path('week_top/', views.week_top, name='week_top'),
    path('post_list/', views.post_list, name='post_list'),
    path('post_list2/', views.post_list2, name='post_list2'),
    path('post_list3/', views.post_list3, name='post_list3'),
    path('post_list4/', views.post_list4, name='post_list4'),
    path('post_list5/', views.post_list5, name='post_list5'),
    path('post2/<int:pk>/', views.post_detail2, name='post_detail2'),
    path('post3/<int:pk>/', views.post_detail3, name='post_detail3'),
    path('post4/<int:pk>/', views.post_detail4, name='post_detail4'),
    path('post5/<int:pk>/', views.post_detail5, name='post_detail5'),
    path('today_top/', views.today_top, name='today_top'),
    path('select/<int:pk>/', views.select, name='select'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('select2/<int:pk>/', views.select2, name='select2'),
    path('delete2/<int:pk>/', views.delete2, name='delete2'),
    path('select3/<int:pk>/', views.select3, name='select3'),
    path('delete3/<int:pk>/', views.delete3, name='delete3'),
    path('select4/<int:pk>/', views.select4, name='select4'),
    path('delete4/<int:pk>/', views.delete4, name='delete4'),
    path('select5/<int:pk>/', views.select5, name='select5'),
    path('delete5/<int:pk>/', views.delete5, name='delete5'),
    path('', views.index, name='index'),
    path('today_detail/<int:pk>/', views.today_detail, name='today_detail'),
    path('chat_top', views.chat_top, name='chat_top'),
    path('chat_detail/<int:pk>/', views.chat_detail, name='chat_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('syllabus/<int:pk>/', views.syllabus, name='syllabus'),
    path('chat_list/<int:pk>/', views.chat_list, name='chat_list'),
]
